### ISSUE TITLE
The reason of applying patch size to moving mnist dataset?

### ISSUE THREAD

**Issue by jhhuang96** [caotong0/SBNet-for-video-prediction#1]
In experiments on moving mnist dataset, shape img data (64*64*1) to (16*16*16). I'm confused about it, is it because of gpu memory and is it appropriate of this way? Thanks!

**Comment by caotong0** [comment]
Yeah, although many codes run it the same way but this isn't a good trick. 
Try conv + deconv(or upsample &conv) to shrink the image size instead.
